//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardPassword
    {
        public int CardPasswordId { get; set; }
        public string CodeNumber { get; set; }
        public string VerifyCode { get; set; }
        public int Flag { get; set; }
        public Nullable<System.DateTimeOffset> CreateTime { get; set; }
        public Nullable<System.DateTimeOffset> ActiveTime { get; set; }
    }
}
