//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Checkout
    {
        public int CheckOutId { get; set; }
        public int AuditType { get; set; }
        public int RoleType { get; set; }
        public int UserId { get; set; }
        public string RealName { get; set; }
        public string VerifyCode { get; set; }
        public string City { get; set; }
        public int KindergartenId { get; set; }
        public int ClassId { get; set; }
        public int ChildId { get; set; }
        public string ChildName { get; set; }
        public int Gender { get; set; }
        public System.DateTimeOffset Birthday { get; set; }
        public System.DateTimeOffset CreateTime { get; set; }
        public string ImageName { get; set; }
    }
}
