//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BabyBus.AutoModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Examine
    {
        public int ExamineId { get; set; }
        public decimal Height { get; set; }
        public decimal Weight { get; set; }
        public decimal Pulmonary { get; set; }
        public decimal Grip { get; set; }
        public decimal StepIndex { get; set; }
        public decimal VerticalJump { get; set; }
        public decimal ResSpeed { get; set; }
        public decimal OneLeg { get; set; }
        public decimal SeatCrook { get; set; }
        public int PushUp { get; set; }
        public string ChildName { get; set; }
    }
}
