//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BabyBus.AutoModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GenderNorm
    {
        public int GenderNormId { get; set; }
        public int GenderNormGroupAgeTypeId { get; set; }
        public int ChildGender { get; set; }
        public string EvaluationType { get; set; }
        public double SpeechLanguage { get; set; }
        public double MathematicalLogic { get; set; }
        public double VisualSpace { get; set; }
        public double Kinesthetic { get; set; }
        public double RhythmMusic { get; set; }
        public double Communication { get; set; }
        public double Intrapersonal { get; set; }
        public double NaturalObservation { get; set; }
        public double TotalScore { get; set; }
    }
}
