//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BabyBus.AutoModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HeightForStandardWeight
    {
        public int HeightForStandardWeightId { get; set; }
        public System.DateTimeOffset CreateTime { get; set; }
        public int UserId { get; set; }
        public int Gender { get; set; }
        public double HeightOffline { get; set; }
        public double HeightOnline { get; set; }
        public double Thin1PintsOnLine { get; set; }
        public double Thin3PointsOffLine { get; set; }
        public double Thin3PointsOnLine { get; set; }
        public double Normal5PointsOffLine { get; set; }
        public double Normal5PointsOnLine { get; set; }
        public double Fat3PointsLower { get; set; }
        public double Fat3PointsOnLine { get; set; }
        public double Fat1PointsLower { get; set; }
    }
}
