//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BabyBus.AutoModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndividualIndexDistribution
    {
        public int IndividualIndexDistributionId { get; set; }
        public System.DateTimeOffset CreateTime { get; set; }
        public int UserId { get; set; }
        public int PhysicalExaEIems { get; set; }
        public double Age { get; set; }
        public int Gender { get; set; }
        public double OnePointsLower { get; set; }
        public double OnePointsOnLine { get; set; }
        public double TwoPointsLower { get; set; }
        public double TwoPointsOnLine { get; set; }
        public double ThreePointsLower { get; set; }
        public double ThreePointsOnLine { get; set; }
        public double FourPointsLower { get; set; }
        public double FourPointsOnLine { get; set; }
        public double FivePointsLower { get; set; }
        public Nullable<int> FivePointsOnLine { get; set; }
    }
}
