//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BabyBus.AutoModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MI_TestDetail
    {
        public int TestDetailId { get; set; }
        public int ChildId { get; set; }
        public Nullable<int> TestRoleType { get; set; }
        public int UserId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public int TestQuestionId { get; set; }
        public Nullable<int> Score { get; set; }
    }
}
