//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BabyBus.AutoModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoticeSummary
    {
        public string KindergartenName { get; set; }
        public string ClassName { get; set; }
        public int NoticeType { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public System.DateTimeOffset CreateTime { get; set; }
        public int KindergartenId { get; set; }
        public int ClassId { get; set; }
        public long NoticeId { get; set; }
    }
}
