//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BabyBus.AutoModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhysicalExaminationResult
    {
        public int PhysicalExaminationResultsId { get; set; }
        public int ChildId { get; set; }
        public int Gender { get; set; }
        public int ClassId { get; set; }
        public int KindergartenId { get; set; }
        public double AgeGroup { get; set; }
        public System.DateTimeOffset TestTime { get; set; }
        public System.DateTimeOffset CreateTime { get; set; }
        public int UserId { get; set; }
        public double Height { get; set; }
        public double Weights { get; set; }
        public double StandingLongJump { get; set; }
        public double JumpWithBothFeet { get; set; }
        public double TennisThrowFar { get; set; }
        public double WalkTheBalanceBeam { get; set; }
        public double SeatBodyFlexion { get; set; }
        public double TenShuttleRun { get; set; }
        public int HeightScore { get; set; }
        public int WeightsScore { get; set; }
        public int StandingLongJumpScore { get; set; }
        public int JumpWithBothFeetScore { get; set; }
        public int TennisThrowFarScore { get; set; }
        public int WalkTheBalanceBeamScore { get; set; }
        public int SeatBodyFlexionScore { get; set; }
        public int TenShuttleRunScore { get; set; }
        public int Fraction { get; set; }
        public int Grade { get; set; }
        public int PhysicalExaminationPlaneId { get; set; }
        public string WeightDesc { get; set; }
    }
}
