//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BabyBus.AutoModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stats_DailyUserReportByKindergarten
    {
        public int Id { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<int> Activist { get; set; }
        public Nullable<int> Increase { get; set; }
        public Nullable<int> AndroidTotal { get; set; }
        public Nullable<int> AndroidActivist { get; set; }
        public Nullable<int> AndroidIncrease { get; set; }
        public Nullable<int> IOSTotal { get; set; }
        public Nullable<int> IOSActivist { get; set; }
        public Nullable<int> IOSIncrease { get; set; }
        public Nullable<System.DateTimeOffset> InDate { get; set; }
        public Nullable<int> KindergartenId { get; set; }
    }
}
