//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BabyBus.AutoModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherInUseSummary
    {
        public int UserId { get; set; }
        public string RealName { get; set; }
        public string Password { get; set; }
        public System.DateTimeOffset CreateTime { get; set; }
        public int KindergartenId { get; set; }
        public string KindergartenName { get; set; }
        public string Description { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public int KindergartenCount { get; set; }
        public bool Cancel { get; set; }
    }
}
