//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BabyBus.AutoModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserId { get; set; }
        public int WeChatInfoId { get; set; }
        public string LoginName { get; set; }
        public string RealName { get; set; }
        public string Password { get; set; }
        public int RoleType { get; set; }
        public int KindergartenId { get; set; }
        public int ClassId { get; set; }
        public string ImageName { get; set; }
        public bool Cancel { get; set; }
        public System.DateTimeOffset CreateTime { get; set; }
        public string OpenId { get; set; }
        public string Phone { get; set; }
    }
}
