//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BabyBus.AutoModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UV_Day15Notice
    {
        public string KindergartenName { get; set; }
        public string ClassName { get; set; }
        public int NoticeCount { get; set; }
        public int MemoryCount { get; set; }
    }
}
