//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BabyBus.AutoModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UV_Stats_PageReportDetail
    {
        public Nullable<int> PageReportType { get; set; }
        public string 被访问功能 { get; set; }
        public Nullable<System.DateTimeOffset> CreateDate { get; set; }
        public Nullable<int> UserId { get; set; }
        public string LoginName { get; set; }
        public string RealName { get; set; }
        public string ChildName { get; set; }
        public int ChildId { get; set; }
        public int KindergartenId { get; set; }
        public string KindergartenName { get; set; }
        public int ClassId { get; set; }
        public string ClassName { get; set; }
    }
}
